In [16]:
# numpy tutorial
import numpy as np
import array as ar

In [5]:
# Version of package
np .__version__

'1.16.2'

In [7]:
# List
L = list(range(10))
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
type(L[0])

int

In [11]:
L2 = [str(c) for c in L]
print(L2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [14]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [17]:
# array from array package
L = list(range(10))
A = ar.array('i', L)
print(A)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [18]:
## Creating Arrays from Pthon Lists
# creating array from numpy package
np.array([1, 4, 2, 5, 3]) # have to be the same type of data

array([1, 4, 2, 5, 3])

In [21]:
np.array([1, 1.5, 0, 15.75]) #upcast if possible

array([ 1.  ,  1.5 ,  0.  , 15.75])

In [22]:
np.array([1, 3, 4], dtype = 'float32') #dtype - set data type

array([1., 3., 4.], dtype=float32)

In [24]:
# nested lists results in multidimensional arrays
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [25]:
## Creating Arrays from Scratch 

In [32]:
# Create a length -10 integer array filled with zeros
zeros = np.zeros(10, dtype=int)

# Create a 3x5 floating-point array filled with 1s
ones = np.ones((3, 5), dtype = float)

# Create a 3x5 array filled with 3.14
fulls = np.full((3, 5), 3.14)

print("zeros = ", zeros, 
      "\n ones = ", ones, 
      "\n fulls = ", fulls)

zeros =  [0 0 0 0 0 0 0 0 0 0] 
 ones =  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 
 fulls =  [[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [46]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the bulit -in range() function)
in_range = np.arange(0, 20, 2)
print(in_range)

# Create a 3x3 array of uniformly distributed 
# random values between 0 and 1
uni_random = np.random.random((3, 3))
print(uni_random)

# Create a 3x3 array of normally distributed 
# with mean 0 and standard deviation 1
normal_random = np.random.normal(0, 1, (3, 3))
print(normal_random)

# Create a 3x3 array of random integers in the interval [0, 10)
int_random = np.random.randint(0, 10, (3, 4))
print(int_random)

# Create 3x3 identity matrix
eye_matrix = np.eye(3)
print(eye_matrix)

# Create an uninitialiezed array of the three integers
# The values will be whatever happens to already exist at that
# memory location
empty_matrix = np.empty(3)
print(empty_matrix)

[ 0  2  4  6  8 10 12 14 16 18]
[[0.52595426 0.81445643 0.06079135]
 [0.08270004 0.8202758  0.5203983 ]
 [0.81319656 0.78928904 0.27067443]]
[[-1.01674967  0.1124708   1.06165887]
 [-0.92260514  1.84836334 -0.49640974]
 [ 1.16323082 -0.10422306  1.14822559]]
[[8 7 0 4]
 [2 7 7 1]
 [9 2 6 6]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1.]


In [48]:
### The Basics of Numpy Arrays
## Numpy Array Attributes
np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size=6) #one dimensional array
x2 = np.random.randint(10, size=(3,4)) #two dimensional array
x3 = np.random.randint(10, size=(3,4,5)) #three dimensional array

In [51]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("x3 type: ", x3.dtype)
print("x3 itemsize: ", x3.itemsize, "bytes")
print("x3 nbytes: ", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 type:  int32
x3 itemsize:  4 bytes
x3 nbytes:  240 bytes


In [65]:
# Array Indexing: Accessing Single Elements
print(x1,"\n",
    x1[0], "\n",
    x1[4], "\n",
     x1[-1], "\n",
     x1[-2], "\n",
      x2, "\n",
     x2[0, 0], "\n",
     x2[2, 0], "\n",
     x2[2, -1])


[5 0 3 3 7 9] 
 5 
 7 
 9 
 7 
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 
 3 
 1 
 7


In [68]:
x2[0, 0] = 12
x1[0]=3.14159
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [75]:
x = np.arange(10)
print(x, "\n", # first 5 elements
    x[:5], "\n", # elements after index 5
     x[4:7], "\n", # middle elements
     x[::2], "\n", # every other element
      x[1::2], "\n",# every other element, starting at index 1
     x[::-1], "\n", # all elements reversed
     x[5::-2] #reversed every other form index 5
     ) 

[0 1 2 3 4 5 6 7 8 9] 
 [0 1 2 3 4] 
 [4 5 6] 
 [0 2 4 6 8] 
 [1 3 5 7 9] 
 [9 8 7 6 5 4 3 2 1 0] 
 [5 3 1]


In [80]:
## Multidimensional subarrays
print(x2, "\n",
      x2[:2, :3], "\n", #two rows, three columns
      x2[:3, ::2], "\n", # three rows, every other columns
      x2[::-1, ::-1], "\n", # reversed together
      x2[:, 0]) # first coluns 
      

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]] 
 [[12  5  2]
 [ 7  6  8]] 
 [[12  2]
 [ 7  8]
 [ 1  7]] 
 [[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]] 
 [12  7  1]


In [81]:
## Creating copies of array
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[12  5]
 [ 7  6]]


In [82]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [85]:
### Reshaping of Arrays
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [87]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [89]:
x.reshape(1, 3) # row vector via reshape

array([[1, 2, 3]])

In [94]:
x[np.newaxis, :] # row vector via newaxis

array([[1, 2, 3]])

In [96]:
### Array Concatenation and Splitting 

## Concatetion of arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [98]:
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [101]:
grid = np.array([[1, 2, 3],
               [4, 5, 6]])
np.concatenate([grid, grid]) #cocncatentae along the first axis

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [103]:
np.concatenate([grid, grid], axis=1) # concatenate along second axis

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [105]:
np.vstack([x, grid]) # vertically stack

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [110]:
y = np.array([[99, 99],[98, 98]])
np.hstack([grid, y]) # horizontal stack

array([[ 1,  2,  3, 99, 99],
       [ 4,  5,  6, 98, 98]])

In [113]:
x = np.arange(1, 20)
x1, x2, x3 = np.split(x, [1, 5])

In [114]:
print(x1, x2, x3)

[1] [2 3 4 5] [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [116]:
grid = np.arange(16).reshape((4, 4))
print(grid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [127]:
upper, lower = np.vsplit(grid, [2])
print(upper, "\n\n", lower)

[[0 1 2 3]
 [4 5 6 7]] 

 [[ 8  9 10 11]
 [12 13 14 15]]


In [131]:
left, right = np.hsplit(grid, [2])
print(left, "\n\n", right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
